### ISSUE TITLE
Questions about the binary encoding

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-specs#11]
I would like to make a pull request to clarify some parts of the [binary encoding specification](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md).

1. Do fields always need to be serialized in order?  I.e., in version 1, do all fields with id 0 need to precede all fields with id 1, even if both fields were known when version 1 was first released?
2. Can a field disallow multiple values?  For example, when a serialized trace context contains multiple trace ids, could that be considered a parse error?
3. Is the version mentioned in [Serialization Rules](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#serialization-rules) a different version from the version described at the start of [General Format](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#general-format)?  If I understand correctly, the `version` field describes something like a major version while the version mentioned in Serialization Rules is like a minor version.

/cc @bogdandrutu

**Comment by bogdandrutu** [comment]
1. For tags, if we have support from the beginning for 3 types and enforce that all the implementation are supporting all types from the initial deployment then we can relaxed that, it will still be good to respect the order but not necessary.
2. This is at per format bases (tags will allow this, trace should probably disallow it).
3. Serialization Rules are specific to version 0 of the general format. so you can see the serialization rules as a minor version.

**Comment by sebright** [comment]
Thanks!  I'll work on a PR.
