### ISSUE TITLE
proposal: Tag scope

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#110]
# Objective
Allow defining tag keys that are never propagated.

# Background
Currently, all tags are propagated. Some however, are only useful in the current process. Examples are "grpc_server_method", "http_server_host", etc. Currently, these are all propagated on outbound gRPC calls even though this probably wasn't the intention.

# Overview
Add a property to TagKey: Propagated boolean

If this property is true, then tags with this key are propagated to remote calls. If set to false, then tags with that key are not propagated out of process.

For the purposes of equality comparisons (for example, in a TagMap), the Propagated property is ignored.

# Alternatives considered
## Have a central whitelist of propagated tags
Having a statically configured whitelist couples together unrelated tag keys in the central place (e.g. gRPC and HTTP tag keys). Having it in a configuration file is more complicated than just having a boolean property. For cases where we categorically never want to propagate the tags (like the grpc_ and http_ tags), this is logically part of the key definition.

**Comment by ramonza** [comment]
My problem with trying to attack the general question rather than just having a flag on the key is that right now we are not in a great situation: we are unintentionally propagating the grpc_ and http_ tags and this can lead to confusing situations e.g. when you have an HTTP service calling a gRPC service.

My goal with this issue was to scope the problem down to just defining a solution to this one problem so that we can get agreement on that and implement it. Without a solution to this problem, as a user I would think twice about installing the gRPC and HTTP plugins if I knew that it would result in unintentional tags being added to all my outgoing calls.

**Comment by sebright** [comment]
I think we should avoid adding scope as a property on the tag key, since it isn't relevant for all uses of keys.  For example, tag keys are used to define views, but views don't need to know whether the tags are propagated.  I also don't think that we should include the tag key scope in the propagation format if only one value of scope is valid for a tag that is propagated (i.e., it should not be possible to receive a tag key on the wire that has propagated=false).  I would rather add a separate API for associating tag keys with scopes, such as my suggestion in https://github.com/census-instrumentation/opencensus-specs/pull/69#discussion_r174633374.

**Comment by sebright** [comment]
> we are unintentionally propagating the grpc_ and http_ tags and this can lead to confusing situations e.g. when you have an HTTP service calling a gRPC service.

I think we are going to temporarily handle the issue of unintentionally propagating gRPC method tags in Java by updating gRPC to remove those specific tags before serializing the outgoing TagContext.

**Comment by ramonza** [comment]
@sebright I like the idea of scope but Go doesn't really have anything like the TagManager object. We would have to have a global variable in the tag package that maintains the scope of each tag key. While this is possible, it seems like a roundabout way of doing it. 

How about making it something a choice when you add the tag to the tag map? Something like:

```
   tag.New(tag.Upsert(key, value, tag.ScopeProcessLocal), tag.Upsert(key, value, tag.ScopeRequest), ...)
```

**Comment by bogdandrutu** [comment]
I think the `Scope` is a nice solution.

**Comment by sebright** [comment]
> @sebright I like the idea of scope but Go doesn't really have anything like the TagManager object. We would have to have a global variable in the tag package that maintains the scope of each tag key. While this is possible, it seems like a roundabout way of doing it.

opencensus-java doesn't have a TagManager class yet, so it would need to be created if we added global state for tags.  It would manage global state similarly to the existing [ViewManager](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/stats/ViewManager.java) class.

> How about making it something a choice when you add the tag to the tag map? Something like:
> 
>    tag.New(tag.Upsert(key, value, tag.ScopeProcessLocal), tag.Upsert(key, value, tag.ScopeReq

I like that this approach avoids making scope a property of the tag, but I'm worried that it would allow inconsistency in scope between different uses of the same tag.

**Comment by songy23** [comment]
Fixed with `TagMetadata`.
