### ISSUE TITLE
Specify how to handle invalid serialized Tag and Trace Contexts.

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-specs#12]
The [binary encoding specification](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md) specifies a general format for serializing fields, but some of the fields may need additional validation.  For example, opencensus-java requires tag keys to [contain only printable ASCII characters and have length less than 256](https://github.com/census-instrumentation/opencensus-java/blob/a9558ba6f680beecaef5a77eda690dda83bc215e/core/src/main/java/io/opencensus/tags/TagKey.java#L34).  opencensus-specs should specify how to apply these restrictions when deserializing contexts, since they can affect the interactions between processes using different implementations or versions of OpenCensus.

/cc @dinooliva @bogdandrutu

**Comment by sebright** [comment]
I'll list some cases where I think we should specify the behavior (or at least state that the behavior is determined by the implementation) and propose ways of handling those cases, as a starting point.  I'll assume that the library provides a function that converts a byte array into a tag context and a function that converts a byte array into a trace context.

1. **How to handle input that doesn't match the general format described in BinaryEncoding.md.** For example, a variable-length field is incorrectly formatted, which means that the start of the next field can't be located.

    The implementation should consider the whole input invalid and shouldn't try to recover any fields.  It should report an error to the user, using language-specific error reporting.  The user can then decide what to do, such as log an error and use an empty tag context.

2. **How to handle an invalid field value that doesn't interfere with locating the next field.**

    The implementation should also consider the whole input invalid in this case.

3. **How to handle an unknown version field, for example, a version that is newer than the implementation.**

    This should also be treated as invalid.

4.  **How to handle an unrecognized field id**

    BinaryEncoding.md already covers some of this.  The parser should stop and only use the fields that it read until that point.  An unknown field id is not considered an error.  The implementation may pass on the rest of the bytes in its requests, for tag context or trace context.

5. **What restrictions to apply to specific fields in a trace context.**

    I'm not sure which types of errors count as parse errors, such as multiple trace ids (#11).

6. **What restrictions to apply to tag keys and values in a tag context.**

    Here are a few options.  (Related: [tag context field definitions](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#tag-context), [tag key restrictions currently enforced in Java](https://github.com/census-instrumentation/opencensus-java/blob/a9558ba6f680beecaef5a77eda690dda83bc215e/core/src/main/java/io/opencensus/tags/TagKey.java#L34), and [string tag value restrictions enforced in Java](https://github.com/census-instrumentation/opencensus-java/blob/a9558ba6f680beecaef5a77eda690dda83bc215e/core/src/main/java/io/opencensus/tags/TagValue.java#L56).)
    - We could have no restrictions, besides requiring valid strings and int64s.  Servers would still need to limit the overall size of the tags that they receive, in order to avoid performance problems.  OpenCensus could provide functionality to help with that, such as a parse function that takes a maximum number of tag bytes to read.
    - We could limit the currently defined tag keys and string tag values to 255 characters and ASCII, and allow those restrictions to be lifted later by adding new field ids.  The current string tag value type would be a 255-character string, and we could add something like a 1000-character string later.  Since there would be no plan to ever change a restriction on an existing field id, we could consider a serialized tag context containing a tag that doesn't meet the restrictions to be invalid, similar to a parse error.  Servers could propagate tags that were created by clients with looser restrictions, because the tags would have higher field ids and could be propagated without being parsed.
    - We could limit the currently defined tag keys and string tag values to 255 characters and ASCII, and plan to allow those restrictions to be changed later, for the same field ids.  We could allow for future changes by ignoring just the tags that don't fit the current restrictions.  For example, an implementation written today would skip string tags with values that are longer than 255 characters, but return the remaining tags that did fit the restrictions.

**Comment by AlekseySanin** [comment]
My $0.02: we should decide on the strategy:
Option 1) Try to recover as much as possible;
Option 2) Abort on error and don't recover anything.

The proposal seems to go along option 2) strategy and it is fine (if this is the route we want to go).

**Comment by rakyll** [comment]
I'd prefer not to partially recover or silently ignoring the invalid input at the tag map builder APIs. Both cases will end up users willingly keep the broken formatted keys/values around. For the deserialization of the tag map from wire, I do not hold any strong opinions. Regardless of what we do (ignore, skip, return error), we shouldn't crash the user's app.

FWIW, we currently do not enforce any limitations to the keys in the Go library and it will require a tiny API change to do so. I'd be glad to agree on a behavior before we finalize the APIs.

**Comment by sebright** [comment]
Should we stop enforcing restrictions on tag keys and values?  I don't think that the restrictions are necessary for the implementation of the library or the serialization format.  Are they needed for exporting data, for example, for exporting to a system that doesn't accept all tag values?

There is also an issue in opencensus-java for providing a way to create tags and values without validation for gRPC, for performance reasons: https://github.com/census-instrumentation/opencensus-java/issues/583

**Comment by sebright** [comment]
I discussed this issue with @dinooliva, @rakyll, @g-easy, @bogdandrutu, @songy23, and others, and we decided on a few points.  I'm planning to make a PR later.

- Restrictions on tags (field 0 of tag context):
  - Tag keys and values can only contain printable ASCII (codes in [32, 126]).
  - Tag keys can have a length in [1, 255].
  - Tag values can have a length in [0, 255].
  - Tags can be serialized in any order.
  - Serialized tag contexts are allowed to have multiple tag fields with the same key.  All but the last value are ignored for each key.
  - Leading and trailing white space is allowed in keys and values.
- How to handle invalid tag contexts:
  - There are no partial failures.  The result of parsing should always be a tag context or an error.  However, unknown field IDs should not be considered an error.  They should be handled as described in https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#deserialization-rules.
  - A tag context that contains a tag that doesn't meet the restrictions above is considered invalid.
  - The first version of OpenCensus stats sets a maximum size for the serialized tag context.  It is 8192 bytes.  This limit should be enforced during serialization and deserialization.  We could make the limit configurable in future versions.
- The API should use strings for keys and values (possibly in a wrapper class), not bytes.

Let me know if I missed anything.

**Comment by sebright** [comment]
Another point from the discussion: Serialization should also have no partial failures.  When a tag context's serialized size would be over the 8192 byte limit, OpenCensus should report an error and not try to serialize a subset of the tags.

**Comment by sebright** [comment]
I have a question about the maximum size for the serialized tags.  Does the 8192 byte limit apply to the whole serialized tag context, just the serialized tag field values, or just the deserialized tag keys and values?  I'm wondering because I thought that the limit should be independent of the serialization format, but that is only true if we look at the deserialized tags.

**Comment by sebright** [comment]
I discussed the last question with @nevinheintze and @dinooliva.  The size limit should only apply to the combined size of the deserialized tags, so that the serialization format does not affect what tag contexts are considered too large.  @songy23 is implementing this for Java in https://github.com/census-instrumentation/opencensus-java/pull/807.

**Comment by sebright** [comment]
In https://github.com/census-instrumentation/opencensus-java/pull/807, the size limit is applied before removing tags with duplicate keys, i.e., a serialized tag context with 10,000 small tags that all have the same key would be considered too large.

**Comment by sebright** [comment]
I updated the specification for Tag Context serialization in #27, #30, and #31.  Since most of the comments on this issue relate to Tag Context, I created a new issue for tracing: #32
