### ISSUE TITLE
Define canonical OpenCensus metrics for Stackdriver Monitoring.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-specs#124]
Currently our Stackdriver stats exporters in all languages are exporting stats as [custom Stackdriver metrics](https://cloud.google.com/monitoring/custom-metrics/). However, custom metrics are not free and are [only available in Premium tier](https://cloud.google.com/monitoring/accounts/tiers#this_request_is_only_available_in_the_premium_tier). Preferably, we should define canonical OpenCensus metrics for [Stackdriver Monitoring](https://cloud.google.com/monitoring/api/metrics), so that users with Basic tier accounts are also able to export stats using our exporter.

**Comment by ramonza** [comment]
I don't think this belongs in this project. This is really a feature request for a single vendor and should probably be directed to them.

**Comment by songy23** [comment]
I agree. I put this issue here since we don't have a cross-language specs repo for opencensus-ecosystem.

**Comment by songy23** [comment]
Closing. Chatted offline, this should be more of a feature request to Stackdriver Monitoring.
