### ISSUE TITLE
Tracing: add specs on Exporting SpanData.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-specs#125]
We have an [Export.md](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/Export.md) for Stats which explains how the data model conversion looks like, it would be useful to have a similar spec for Tracing SpanData.

**Comment by ramonza** [comment]
Exporting views as metrics is pretty complicated. I don't think exporting spans is really that complicated. What do you expect such a document to say?

Was there some question that prompted you to create this issue that you hope the doc would answer?

**Comment by songy23** [comment]
Probably on data model mapping (especially on encodings). I'm asking because I think we can have general guidelines for users who want to implement tracing exporter, but if it's straightforward enough, we may just ask them to take a look at the existing exporters instead.

**Comment by ramonza** [comment]
I think most of the important details are language-specific: memory ownership for Span objects, whether things should be synchronous/asynchronous, how errors are signaled, cancellation, flushing, etc.

**Comment by songy23** [comment]
Sounds good, then there's not much meaning on adding a cross-language spec. It's better to defer the guidelines to each language.
