### ISSUE TITLE
Add document about all HTTP supported propagation formats

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#13]
We need to document what HTTP formats we support.

**Comment by adriancole** [comment]
You are referring to propagation formats, right? (Not export formats.. or
both!)

**Comment by bogdandrutu** [comment]
Just propagation. Updated the title.

**Comment by ramonza** [comment]
Things we should specify:
* Span name format on client and server
* Message sent/received events
* Status set on client and server spans
* How to annotate the Span (if at all) with describing headers, HTTP method, path, HTTP version

**Comment by ramonza** [comment]
This should describe trace propagation as well as tag propagation. It should maybe also recommend a default behavior for both server and client.

**Comment by songy23** [comment]
Added in https://github.com/census-instrumentation/opencensus-specs/tree/master/encodings#formats.
