### ISSUE TITLE
Providing tags without context objects

### ISSUE THREAD

**Issue by fabxc** [census-instrumentation/opencensus-specs#140]
Contexts are currently the only way to provide tag values (AFAICT), which makes sense for the majority of metrics, which are scoped to a some kind of request and certainly for traces.

For metrics there are many cases though, where one just wants to measure some state of application internals, e.g. the length of a queue.
It would be helpful if one could initialize a static set of tags somehow (e.g. queue identifier) without forcing a context object into all APIs for the sole purpose of setting a metric tag. It may actually force developers to significantly refactor and break their APIs if they want to add OC instrumentation to existing code.

I think similar issues would arise in practice for an OC logging API.

@jkohen

**Comment by ramonza** [comment]
As an example, do you mean (in Go) something hypothetically like:

```go

stats.Record(ctx, myMeasure.M(1), stats.WithTag(TagKeyQueueName, "my-queue-1"))
```

**Comment by songy23** [comment]
In Java you can use [MeasureMap.record(TagContext tags)](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/stats/MeasureMap.java#L91), which takes additional tags when recording without putting them into context.

**Comment by fabxc** [comment]
Looks like Java supports what I was thinking of.
I was thinking of a similar Go API but currently the measure argument is already variadic, so that would mean a breaking API change. Though I think recording multiple measure at once is infrequent enough for this to be ok.

**Comment by fabxc** [comment]
I see, that makes sense. Probably best to just add a separate methods that takes an additional tag slice then?

**Comment by rakyll** [comment]
I also think adding a separate function would be the best. It would be also easier to document the difference. What about the following?

```
func RecordWithTags(ctx context.Context, tags map[tag.Key]string, m ....Measurement)
```

**Comment by ramonza** [comment]
This is an opencensus-go specific discussion, let's continue there.

**Comment by songy23** [comment]
I think we already have that specification?

> [Users should record Measurements against a context, either an explicit context or the implicit current context.](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/Record.md#recording-stats)

Maybe we can add another sentence says users can put additional tags in the explicit context.

**Comment by rakyll** [comment]
Maybe we can say something like "It should be easy to record with non-propagated tags." and it is implementation detail how you achieve it.

**Comment by songy23** [comment]
> Maybe we can say something like "It should be easy to record with non-propagated tags." and it is implementation detail how you achieve it.

Exactly. In Java (may also apply to other languages) we think it's better to just use the `TagContext` class. For example, with `Map` users need to do:
```java
private static final Map<TagKey, TagValue> extraTags = 
  ImmutableMap.builder().put(key1, value1).put(key2, value2)....build();
measurementMap.recordWithTags(currentTagContext, extraTags)
```

While with `TagContext`:
```java
private static final TagContext contextWithExtraTags = 
  tagger.currentBuilder().put(key1, value1).put(key2, value2)....build();
measurementMap.record(contextWithExtraTags);
```
Looks like an API that takes a `Map` doesn't simplify the code, while it requires creating a new `Map` which may introduce more overhead.

Also as @sebright mentioned:

> (using `TagContext`) allows the library to skip creating the map as an optimization when OpenCensus isn't enabled.

Original discussion: https://github.com/census-instrumentation/opencensus-specs/pull/145#discussion_r203156946
