### ISSUE TITLE
Support X-B3-ParentSpanID header (shared spans)

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#143]
Moved from: https://github.com/census-instrumentation/opencensus-go/issues/810

Zipkin instrumentation by default sends the parent span ID when the client and server side share a span ID. It would be interesting to see if we could support this shared span approach when exporting to Zipkin.

**Comment by bogdandrutu** [comment]
@ramonza Zipkin added support for non-shared client/server spans. Why do we need to support this?

**Comment by ramonza** [comment]
spoke offline. I need to do more experiments to see if we can live without this for Istio/Envoy. I will re-open if not.
