### ISSUE TITLE
Add support for Float64 in the AttributesValue

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#172]
This proposal comes from https://github.com/census-instrumentation/opencensus-go/issues/900. Any opinions on this?

**Comment by bogdandrutu** [comment]
@songy23 and @ramonza please +1 this proposal so that we can move forward with it.

**Comment by songy23** [comment]
I think we're good to go now.

**Comment by bogdandrutu** [comment]
It seems that we have agreement on this.

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu should this be merged than?
