### ISSUE TITLE
Code ownership

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#174]
# Background
Our organization grew in the past months and our current model of code ownership will not scale very well. Currently we have a large group of people that have write access to all repositories and PRs can be merged without a proper review from one of the repos owner.

Some repos contain multiple packages/artifacts (for example the opencensus-java) and we would probably want to have different owners for different packages (for example would be great to have @ubschmidt2 as owner for the agent work that he implemented).

# Proposals
This section contains few proposals on how to solve this issue, with pros and cons.

## Limit the people with write access
This means that we need to delete the current teams (in the organization) and define for each repo a new team that has write access (separate from the admin team). This will require that all PRs are merged only by the team with write access, all team members will have ownership for the entire repo (this may not be a problem for repos like opencensus-go where all the contrib packages are in different repos).

## Use GitHub code owners
GitHub added a new feature called code owners, see [here](https://blog.github.com/2017-07-06-introducing-code-owners/). We can use this feature combined with the branch protection rule to enforce one code owner approval. With this we can enforce owners at directory/files level as well as we allow PR owners (with write access) to merge their PR once it is approved.

**Comment by g-easy** [comment]
Code owners seems like the right approach, particularly because it's fine-grained.

In the first proposal, do you mean that even after approval, someone outside of the write-access-team won't be able to click merge on their own PR?

**Comment by bogdandrutu** [comment]
I would start playing with the owners in 2 repos (specs and proto). If in 1-2 weeks we find that this works fine we will implement in all the repos in this org.

@g-easy yes the author will not be able to press merge.

**Comment by g-easy** [comment]
Not being able to merge my own PRs (sometimes timing and/or ordering is important) would be bad.

**Comment by songy23** [comment]
This is already enforced in Java, Go, Python, etc.
