### ISSUE TITLE
Link to community meetings?

### ISSUE THREAD

**Issue by zoidbergwill** [census-instrumentation/opencensus-specs#187]
I see the [Process](https://github.com/census-instrumentation/opencensus-specs/blob/master/Process.md#step-2-approval) document mentions regular community meetings. Where would I find more information out about those? Sorry if I missed an obvious link somewhere.

**Comment by songy23** [comment]
cc @shahprit

**Comment by shahprit** [comment]
https://docs.google.com/document/d/1AZEJ-ve9Qj9SlL5xIFU7drNWPfx2CLDIRvUzZsV7AR0/edit?usp=sharing

**Comment by rakyll** [comment]
Also sent out https://github.com/census-instrumentation/opencensus-specs/pull/194.
