### ISSUE TITLE
Structured logging/event creation

### ISSUE THREAD

**Issue by nfisher** [census-instrumentation/opencensus-specs#197]
Not sure whether people feels this is a fit but I was reading through the Honeycomb docs and noticed they have the concept of an "Event"[1] and provides the following interface;

```
  ev := libhoney.NewEvent()
  ev.Add(map[string]interface{}{
    "method": "get",
    "hostname": "appserver15",
    "payload_length": 27,
  }))
  ev.AddField("duration_ms", 153.12)
  defer ev.Send()
```

Looking at it sideways it seems a good fit for a standard structured logging interface when used with a printer. For services like honeycomb that have the concept of an "event" it could be shipped directly. If the spans context were submitted as part of the NewEvent() I could see it automatically tagging the event with related span info like parent, root, etc. In turn this would make the stackdriver trace console (see below) automagically pick-up related log lines without me having to manually tag them.

<img width="570" alt="screen shot 2018-10-10 at 10 21 59" src="https://user-images.githubusercontent.com/18616/46739348-b7ffc500-cc76-11e8-8dc6-7156bbe0c4c7.png">

1 - https://docs.honeycomb.io/sdk/go/#building-and-sending-events

**Comment by adriancole** [comment]
meta comment: we discussed originally that census would add features that
have at least one oss implementation. I dont know the landscape to know if
there is an open source honeycomb

**Comment by nfisher** [comment]
Thanks @adriancole!

Using a "printer" implementation (similar to the trace console printer) I would see it as a structured log interface that could be shipped to the [ELK Stack](https://www.elastic.co/elk-stack) or similar systems.

Essentially a log line and event are more or less synonymous. I guess I kind of look to OpenCensus as being a library for "observability" and events/logging is the one thing that's absent. I could see getting the root span ID in OpenZipkin/Jaegar and then using it to search for related "events" in ELK.

Feel free to close if it's out of scope.

**Comment by sebright** [comment]
#130 is related.

**Comment by nfisher** [comment]
Will close as #130 is related and I’ll look at adding anything under this that’s missing there.
