### ISSUE TITLE
Provide a way to avoid propagating tracing and tag metadata

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#204]
In many cases the easiest and recommended way to use OpenCensus is to rely on framework integration. For example, our gRPC and HTTP plugins. These plugins do a lot of things: they record stats, generate trace spans around requests/RPCs and read and write header metadata to propagate traces and tags.

In many cases, this propagation is not desirable. For example, if your service talks to an external API that you don't control there is no reason to send tracing metadata and sending tags is a potential dangerous because we can't make assumptions about what private information might be in them.

At the same time, we don't want to discourage users from installing and using the OpenCensus plugins, since they provide so much other functionality besides propagation. For this reason, we propose that libraries should provide a way for HTTP and gRPC (and any other instrumentation) plugins to be installed in such a way that they *do not* propagate metadata.

**Comment by songy23** [comment]
Superseded by `TagMetadata`.
