### ISSUE TITLE
Proposal: join CNCF as the API specification for metrics and spans

### ISSUE THREAD

**Issue by hauleth** [census-instrumentation/opencensus-specs#234]
[Cloud Native Computing Foundation](https://cncf.io) is foundation that works on building "ecosystems and fosters a community around a constellation of high-quality projects that orchestrate
[…] microservices architecture". There would be a little bit conflict between project that is already present there (OpenTracing), but OpenCensus provide slightly more, so I think that this project has potential to be accepted to the Foundation projects.

**Comment by tsloughter** [comment]
Already part of the roadmap. There is both work being done to consolidate OT and OC (not really sure what that'll look like in the end) and CNCF, see governance section of https://docs.google.com/document/d/1laNafieoA6u6e8bzMIq29JWW8tYeWQqktdr_nM8G6T0/edit#heading=h.rgzndqcl2aun

**Comment by mtwo** [comment]
Yep, as @tsloughter said this is in progress :)

**Comment by bogdandrutu** [comment]
I am happy to close this issue :)
