### ISSUE TITLE
Consider supporting b3 debug flag

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-specs#260]
The b3 spec includes a [debug header](https://github.com/apache/incubator-zipkin-b3-propagation#debug-flag) (`X-B3-Flags`) to force a request to be sampled. We [read the header](https://github.com/c24t/opencensus-java/blob/c0f3a4cf4c437b9a4ac983f1bd44781f60d0182f/impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java#L104-L105), but only use it to set the sampling bit on `TraceOptions`. This gets encoded as `X-B3-Sampled` on the way back out.

We may not want to to pass the debug flag to samplers, but we do need to store it somewhere in-process to propagate `X-B3-Flags`. We don't do this now, which breaks debugging for downstream services.

How can we support this flag? For comparison, Brave [stores the debug flag on the trace context](https://github.com/openzipkin/brave/blob/a3de48060298adce5d9def311b5191d661b616d8/brave/src/main/java/brave/propagation/SamplingFlags.java#L17), and Zillow forked the python client to [store it on `TraceOptions`](https://github.com/zillow/zopencensus-python/commit/9f9edeb0decea7a9ba9081dcb0eaed6bccdda891). That is, they're using one of the reserved (but otherwise unused) [trace flags](https://github.com/w3c/trace-context/blob/master/spec/20-http_header_format.md#trace-flags) to represent debugging. Unless we change the trace context spec, this solution won't work for us.

What do you think about storing the flag on `Tracestate`? Vendors already use this to store out-of-band information that doesn't fit into our span model.

See the original issue in the python client repo: https://github.com/census-instrumentation/opencensus-python/issues/612.

cc @dinooliva

**Comment by c24t** [comment]
cc @LokiW, who's working on Zillow's fork.

**Comment by SergeyKanzhelev** [comment]
`tracestate` is a great place for debug flag.

**Comment by adriancole** [comment]
FWIW this is the primary reason we added b3 single header format. by
placing b3 single format in trace state you have authoritative not just
debug but also sampled which is subtly different from how tracecontext
defines it (in b3 it is a trace scoped decision whereas in trace context it
is more subtle)

in other words you can use b3 single as a tracestate entry

**Comment by c24t** [comment]
Thanks! We'll store the single header format in `tracestate`, and it sounds like we don't need to make any changes to the spec.

**Comment by dinooliva** [comment]
Question for clarification: What is the intention behind tracestate?

My original understanding of tracestate was that it was for users/applications to define keys/values that would be propagated for their use e.g. to add vendor-specific extensions to the trace system. In this case, it seems odd to me that the tracing system itself would be defined in terms of tracestate - i.e. if DEBUG is a fundamental feature of the tracing system, shouldn't it be built into the tracing system not added as an extension via tracestate?

**Comment by adriancole** [comment]
hey dino.

w3c tracecontext spec drifted from major things, which is what forced
us (zipkin) into a corner of needing to still use b3. The most major
thing was the change they made to turn the trace sampled flag into an
awkward "recorded" one which isn't trace consistent. Debug was another
feature, but if we can't even get sampling back to where it was (also
used exactly same in aws etc), then no point discussing debug. It was
this change about sampling made by some OT folks that made the spec
largely useless for interop

**Comment by dinooliva** [comment]
I see, that makes sense (unfortunately) - thanks for the clarification!

**Comment by adriancole** [comment]
ps here's when the spec intentionally broke and started a path to the
confusing recorded flag
https://github.com/w3c/trace-context/pull/142#issuecomment-415237146
here's a request to rename the confusing recording flag to sampled
(likely leaving semantics alone)
https://github.com/w3c/trace-context/issues/265

**Comment by dinooliva** [comment]
Thanks for the background - very interesting reading - so we can use tracestate to define the features we actually want/need, although we end up defining yet another standard - doesn't seem to be much we can do about that at this point though.

**Comment by adriancole** [comment]
still a draft... sense can still converge. I gave up trying but maybe others can
<img width="473" alt="Screen Shot 2019-04-24 at 10 06 17 AM" src="https://user-images.githubusercontent.com/64215/56627508-0f004100-6681-11e9-8d0b-a2fd020279dd.png">
