### ISSUE TITLE
document aggregation functions that should be provided

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#38]
* Sum
* Distribution
* Latest
* Mean
...

**Comment by songy23** [comment]
Should this be an aggregation or a window type? I remember we plan to add a new `Gauge` window in v2, which represents the same thing to `Latest`.

**Comment by rakyll** [comment]
Isn't this a view that doesn't require any aggregation or window?

**Comment by rakyll** [comment]
Sorry, I pressed "comment" too soon. I wanted to ask whether a gauge is a view with no aggregation or window.

(Btw, this issue title and description is not representation what we are discussing.)

**Comment by bogdandrutu** [comment]
This is now defined in https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/DataAggregation.md.
