### ISSUE TITLE
Sampling expectations and propagation when not sampled

### ISSUE THREAD

**Issue by tsloughter** [census-instrumentation/opencensus-specs#4]
There is need for defined points a library or instrumentation should invoke the configured sampler logic and how/what should be propagated to any children of a disabled span. 

When the sampler should be called:

* entering a service (the initial creation of a span or context from a propagated trace context)
* root span creation
* user set a specific sampler for that Span (see SpanBuilder in Java)

In the event the sampler returns `false` and the trace context is propagated to another service, the trace id and parent span id of the span would be propagated. For example if we have services `A`, `B` and `C` with calls resulting in the propagation `A->B->C` and `B` is disabled by its sampler logic then the trace context received by `C` will have the trace id and span id that was originally sent from `A` to `B`.

Note that the fact a parent service who propagated context to a service was or wasn't sampled can be used in the sampling decision of the service, but it having been sampled or not does not create a strict requirement one way or the other (unless of course the configured sampler logic on the service is simply to return the decoded boolean sent with the trace context).

Additionally this defines that once a trace is enabled within a service through its sampler logic, the children within the service of that span do not check with the sampler logic. Meaning within `A`, `B`, or `C` there can not be gaps in the trace.

**Comment by adriancole** [comment]
@bogdandrutu this is actually a big part of what I was mentioning earlier today. we need to define what the semantics are for propagating a "no". Biggest deal is here, where if we provision anyway, we can create gaps which could possibly not be filled.

ex. A ->(yes) B -> (no) C -> (no) D -> (yes) E
if this looks the same as a passthrough (ex we propagating incoming span ID on no), then it looks the same as a trace A -> B -> E (which will have no gaps). However, other consumers of id will be confused (like log entries)

**Comment by bogdandrutu** [comment]
I would call this done. we wrote the document about sampling, if more infos are needed we should open a new issue with concrete action items.
