### ISSUE TITLE
Remove Window from View

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#47]
Objective
---
Simplify view definitions by removing the Window, effectively making everything Cumulative. In particular, remove Interval windows.

Background
---

No backends we are aware of support doing anything meaningful with Interval counters. Instead, generally, you submit cumulative metrics from each task and the backend derives values for time intervals by taking the difference between the values at the start and end of the interval of interest. 
Some backends support delta submissions, but these are not the same as Interval. This is really an implementation detail of the Exporter but the logical view is the same.

The only use of Interval views is in-process for z-Pages. Internally at Google, they are also used for load balancing.

The proposal is therefore to:
* Eliminate Window as a concept from View definitions
* Move the windowing logic into the z-Pages

This achieves a simplification of the view definition and avoids confusing users by presenting them with the Window option that almost never makes sense for them to configure themselves. 

Requirements and Scale
---

This removes API surface area from all languages and from protobuf view definitions. We still need this functionality in z-Pages. But similar to backends, z-Pages can compute the values over intervals from the cumulative values. This is possible for sum, count and distribution aggregations.

Design Ideas
---

Remove Window from view definition proto and data model docs. This entails removing both  Cumulative and Interval. The semantics are that Cumulative is assumed.

In stats.proto, remove Interval*. Propagate this change to code wherever intervals are used.
From all view names, remove the word "cumulative", "window", and "interval". Delete all "hour" and "minute" views (gRPC). z-Pages still need to display metrics over the last hour/minute (should we add something in-between, like 15min?). This can be implemented by z-Pages using an Exporter that keeps an hour worth of samples and computes the change/rate by subtracting starting values from ending values. For example, consider the gRPC view of client request latency distribution (currently called "grpc.io/client/roundtrip_latency/cumulative", renamed to grpc.io/client/roundtrip_latency" if this design is accepted).
This is a Distribution. A distribution is just a fixed set of Counts, one for each bucket. To determine the correct bucket count for the last minute, take the value recorded a minute ago and subtract from the current value. You might not have a recording from exactly one minute ago or exactly the current value but you can use linear interpolation to get an approximation. A similar approach works for any count or sum (anything where a difference operation is defined). Mean can be derived from count and sum.

So in this simple scheme, we record a new sample every time our Exporter is called and remove samples older than an hour.

Windows on aggregate functions
----

Some aggregate functions require windows. For example, something like Prometheus' Summary metric, or sketch-based approximate data structures. These cannot be subtracted so it's not possible to derive values for time intervals from cumulative values. This doesn't apply to any of the aggregation functions we currently support (all count based). 

In future, if we want to add aggregate functions that require a time window, we should add the time window on the aggregation function itself. This is not the same thing as having a time window on the view since in these cases, Cumulative is usually not a valid time window (number of distinct clients seen since application start is not useful, but number of distinct clients in the last hour is). So even if we add such functions, the current Cumulative/Interval representation would probably not make sense. This design does not preclude such future aggregate functions.

Alternatives Considered
---

1. Do nothing. Leave intervals and windows in place. This keeps the API and implementation complexity (interval is more complicated than cumulative) and provides very little benefit since it's only used in z-Pages.
2. Remove interval but keep cumulative interval. Since cumulative is the only window type supported, it should just be assumed. If we need to add a window type in future, we can always restore the window type (defaulting to cumulative).

**Comment by bogdandrutu** [comment]
From z-pages (rpcz) we decided to remove max latency for the moment and maybe later add percentiles support.

**Comment by bogdandrutu** [comment]
I think we can call this done. Java, Go and C++ implemented this. Other languages do not offer stats yet.
