### ISSUE TITLE
Sanitization rules on view names/tag keys for exporters

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-specs#50]
In OpenCensus we have restrictions on view names and tag keys, that they should be ASCII strings with < 256 characters. However, when we export views and stats to other monitoring backends, those backends may have different restrictions, and we may need to do `sanitization` on views and/or tag keys. 

For example, [Prometheus only accepts metrics and label names with alphanumeric characters and underscores](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels), and in [Go](https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/prometheus/prometheus.go#L276) and [Java](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Collector.java#L181) exporters, we need to sanitize views and tag keys by replacing all other characters with underscores. However, as @jcd2 described in https://github.com/census-instrumentation/opencensus-go/issues/173, the sanitization may lead to some unexpected cases. For example, suppose we have "grpc/io/some/view" and "grpc/io/some-view", they will be both sanitized to "grpc_io_some_view", and Prometheus will reject the second one.

We need some cross-language specs on how to deal with such cases. Currently Go and Java exporters just do the santization and have the other monitoring client libraries deal with the corner cases. 

/cc @bogdandrutu @dinooliva @jcd2 @odeke-em @rakyll @ramonza

**Comment by rakyll** [comment]
I think this is a duplicate of https://github.com/census-instrumentation/opencensus-specs/issues/35.

**Comment by ramonza** [comment]
The problem with sanitization is that it quickly becomes tricky if you really want to prevent losing information. You need to start defining escaping protocols and that seems like a big overreach in complexity.

IMO the right thing to do is to not permit invalid view name / exporter combinations. We could either throw an error or just log a warning if they were used together. It's usually going to be the same person registering views and exporters so they will have the opportunity to fix the problem if we tell them about it.

**Comment by songy23** [comment]
Oh I didn't notice that issue. Closed this one in favor of https://github.com/census-instrumentation/opencensus-specs/issues/35.
