### ISSUE TITLE
Remove Mean aggregation.

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#56]
@jkschneider commented:

> I worry about this one. Mean isn't aggregable across dimensions, so doesn't seem particularly useful in general. For distribution summary type metrics, shipping a total amount and count is generally sufficient to be able to derive a truly aggregable mean. Some systems are so aware of this problem that they provide a standard query function OOTB (see dist-avg). Some monitoring systems expect mean to be pre-computed as a matter of convention, but could shipping mean be an exporter concern for those systems?

**Comment by bogdandrutu** [comment]
Based on the sentence "prefer minimal API initially because we can always remove later" I would propose this to become a no support for Mean aggregation.

Changed the name of the issue and assigned to the language people to remove the support.

**Comment by g-easy** [comment]
opencensus-cpp API doesn't have mean (except as part of distribution).

**Comment by songy23** [comment]
I think this can be called done now. Go and Java have removed/deprecated Mean, and C++ doesn't have Mean in the first place.
