### ISSUE TITLE
How should we support exporting to local aggregation agents?

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-specs#63]
Some metrics backends mandate their own local agent/sidecar for aggregation. Examples of this are DataDog (dogstatsd) and CloudWatch (others?)

In these cases, we still want to allow users to take advantage of OpenCensus instrumentation in libraries (e.g. gRPC, HTTP), but we don't want OpenCensus to do in-process aggregation. Instead ideally, OpenCensus should directly send raw metrics events to the vendor agent.

**Tags**: We probably still want to configure which tags get sent to the vendor sidecar and how

We also might want to configure in-process downsampling to avoid overwhelming the agent (this is supported by the statsd protocol).

We could provide some sort of hook that stats.Record would call but just a Measurement is probably not enough to send to the vendor agent. For example, statsd needs to know what [metric type](https://github.com/etsy/statsd/blob/master/docs/metric_types.md) you want to record and Measure does not really specify this.

**Comment by savaki** [comment]
I ran into this issue when implementing the datadog Exporter.  `dogstatsd` prefers to receive independent measurements and perform the aggregations internally.  Much of the Exporter was an exercise in de-aggregating the View back into its constituent Measurements.

Agreed the measurement isn't quite enough.  The supported metric types,
* counters
* gauges
* histograms
* sets

The general reporting format for dogstatsd is `metric type, metric name, value` Timestamp will be implied by when the metric was received by the agent

**Comment by savaki** [comment]
That would work for me.

**Comment by ramonza** [comment]
We should not have an unbounded buffer. We can keep only a fixed number of points. I am ok with this as long as we are happy to drop points after we reach some fixed number (it can be pretty high since points are small).

**Comment by ramonza** [comment]
Also how does this address the issue of telling statsd what metric type to use?

**Comment by songy23** [comment]
Obsolete.
