### ISSUE TITLE
tags: implement spec for HTTP propagation

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-specs#65]
While working on the interop tests across Go and Java, one of the requirements was that tag propagation be tested for both gRPC and HTTP. In Go, we only have tag propagation for gRPC which
sends tags as an encoded blob in the metadata headers(I don't see a spec here though, so perhaps also file an issue for it?).

This issue is a request for us to work the spec for it and I left reminders for that such as
https://github.com/census-instrumentation/opencensus-experiments/blob/c6a2b2d00eb184da894de2ae14ef5dce4ab45951/integration/go-http-client/client_test.go#L122
and I also filed an issue on the Go package https://github.com/census-instrumentation/opencensus-go/issues/537

**Comment by songy23** [comment]
FYI the gRPC encoding spec is https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md.

/cc @HailongWen

**Comment by odeke-em** [comment]
>FYI the gRPC encoding spec is https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md.

@songy23 in deed, that's for encoding, I meant for propagation though. We don't specify how either gRPC or HTTP transports will propagate tags.

**Comment by songy23** [comment]
That's right - sorry for the confusion. I think we could open another issue to add gRPC propagation specs. (I remember there are some docs on gRPC propagation, but clearly they are not in this repo currently.)

**Comment by odeke-em** [comment]
Cool @songy23 I've opened https://github.com/census-instrumentation/opencensus-specs/issues/66, thanks.

**Comment by songy23** [comment]
We're moving forward with W3C correlation context. See https://github.com/census-instrumentation/opencensus-specs/tree/master/encodings#formats.
