### ISSUE TITLE
tags: implement spec for gRPC propagation

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-specs#66]
We lack a spec for tags propagation using gRPC although a couple of the packages already have it, but we've found some issues like in the Go implementation https://github.com/census-instrumentation/opencensus-go/issues/541 where "method" was inserted during propagation.

Also this came up in the equivalent HTTP propagation specs request issue  https://github.com/census-instrumentation/opencensus-specs/issues/65

**Comment by bogdandrutu** [comment]
@ramonza this will be covered by your doc related to tag scopes correct?

**Comment by songy23** [comment]
I believe this can be marked as resolved with #233. Feel free to reopen if there're further questions/comments.
