### ISSUE TITLE
What are the protobuf models for? Where is the aggregation daemon?

### ISSUE THREAD

**Issue by rektide** [census-instrumentation/opencensus-specs#68]
It's confusing to me that OpenCensus integrates so much logic into the client libraries. I'd rather expected a well tuned, performant transit of the app observability data to a OpenCensus aggregation daemon. That would greatly reduce the implementation burden on each platform, and allow polyglot nodes to still effectively aggregate data.

We have a robust model of ProtoBufs, which really out of the gate made me think all this was coming- I thought that was going to be the basis for having client instrumentations talk to the local OpenCensus node-aggregator daemon. I thought the ProtoBufs would be part of how the client instrumentation spoke to the local aggregator-daemon, and how the local-aggregator daemon talked to other higher up daemons. But I haven't seen anything like that, and I'm really wondering why these protobuf definitions were created in the first place. If each platform is going to be completely standalone, it seems like serialization to and from protobuf would be a major hit vs directly targeting the language, & there's no use that I can see for protobuf if the client instrumentation only talks via an "exporter" that speaks some other already defined spec.

I also was expecting the aggregation daemon was going to evolve a runtime remote API (http or grpc) to control the aggregation system. Use cases like #46 - telling OpenCensus to make sure it exports all the samples it has on a specific request, retrospectively - seem like the kind of place where I would expect to have an HTTP or grpc service that I can use to talk to and control my local-aggregations.

A lot of these ideas about capabilities stem from the post ["Google's Approach to Observability,"](https://medium.com/@rakyll/googles-approach-to-observability-frameworks-c89fc1f0e058) especially at the end, talking about "Aggregation of data".

There's a huge disconnect in my mind. Why is there no aggregation daemon, and why is each client starting from scratch? What purpose do these protocol buffers serve, if the client instrumentation only has a native API and exports via some other remote API?

**Comment by bogdandrutu** [comment]
@rektide you are 100% correct. For the moment they server just as data models for our APIs and exporters. We are planning (in the next month) to release a gRPC service to control the library (aggregations, tracing sampler, etc.) as well as get access to the raw data (Span proto for example).

**Comment by wkiser** [comment]
@bogdandrutu any updates on when the gRPC service you mentioned will be released? Really looking forward to it since, like @rektide mentioned, it would let us greatly simplify the language libraries.

**Comment by rektide** [comment]
i'm kind of taken recently by stripe's [veneur](https://github.com/stripe/veneur).

they invented their own protobuf structures ["ssf"](https://github.com/stripe/veneur/tree/master/ssf) that applications can use to send metrics/trace/event data to their aggregator, and that that the aggregator can forward along upstream. there's a grpc proxy they have as part of this package that seems to embody a lot of that work.

i continue to think the model of having a kubernetes "daemonset"-style aggregator on each box, that apps talk to, and which configurably buffers, spools & forwards observability data is what the opencensus protobufs ought to be most useful for, and i think veneur is showing a whiff of these necessities. i'm excited to see opencensus move beyond these client libraries that each re-implement a suite of exporters & move towards having it's own fast, well defined transport & aggregation system, built around the core data model opencensus has at it's heart.

**Comment by BrianChristie** [comment]
I found this while doing some searching after a recent tweet about runtime configurability of OpenCensus.

Just wanted to check in that the plan is still to have some kind of runtime aggregation daemon, and if there's possibly any discussion or design docs elsewhere that I haven't found yet?

**Comment by rakyll** [comment]
There is a prototype and several drafts so far. @bogdandrutu  should update this issue with the state of the work. See https://github.com/census-instrumentation/opencensus-service for the goals.

**Comment by rakyll** [comment]
Bogdan pointed out the comprehensive design document is at https://github.com/census-instrumentation/opencensus-proto/tree/master/opencensus/proto/agent.

**Comment by zoidbergwill** [comment]
Sorry to ping this thread for no reason, but the link above has changed because things moved into `src/`, to [`https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/README.md`](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/README.md)

**Comment by songy23** [comment]
Obsolete.
