### ISSUE TITLE
Java and Go are incompatible for SD monitoring

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#83]
If a user uses Java and Go and add a IntMeasure, then define a view with a Sum aggregation the data sent to SD monitoring will be incompatible because Java defines the MetricDescriptor with a value type INT64 but Go defines the MetricDescriptor with a value type DOUBLE.

This will cause errors. we need to make a decision if we support or not int64 measure if we do so we need to be compatible.

**Comment by songy23** [comment]
I remember we had a discussion with @nevinheintze long ago and agreed that supporting int64 measure at API level is useful. For exporting to SD monitoring, I think `MetricDescriptor` also needs to be consistent with the `Measure` type, i.e int64 `Measure` should be converted into Int64 `MetricDescriptor`.

**Comment by rakyll** [comment]
Until we decide whether we should remove or keep int64 sums, I sent out a fix for the Go implementation: https://github.com/census-instrumentation/opencensus-go/pull/644.

**Comment by bogdandrutu** [comment]
@rakyll thanks. I think this is good to fix the current situation. I will change this to a discussion to document the arguments for int64.

**Comment by rakyll** [comment]
As a side note, Go aggregates int64 measures as float64 sums. We also need to address this issue. See https://github.com/census-instrumentation/opencensus-go/issues/646.

**Comment by bogdandrutu** [comment]
I will close this issue and open a new one which is focused on making all stats consistent for types and units.
