### ISSUE TITLE
Suggestion to add fixed rate sampling / rate-limiting

### ISSUE THREAD

**Issue by tylerbenson** [census-instrumentation/opencensus-specs#9]
The [proposal describing sampling](https://github.com/bogdandrutu/opencensus-specs/blob/8936814ca15bef0242311c83797e266c69b8969d/trace/Sampling.md#what-kind-of-samplers-does-opencensus-support) suggests adding support for random percentage of traffic.  While simple to implement and predictable for purposes of extrapolation, this has the potential to make it more difficult for tuning to the load of the tracing system.  Random sampling also has problems when dealing with significant swings in traffic.

I'd like to suggest we include a description for a fixed rate sampler, where instead of sampling a percentage of the traffic, the sampler captures at most X traces per some time period.  One potential java implementation could utilize something like `com.google.common.util.concurrent.RateLimiter`.  This has the benefit of capturing a higher percentage of traces for a low throughput system, while maintaining a consistent flow of traces to the tracing system regardless of the traffic changes.

**Comment by adriancole** [comment]
on this note one thing likely to enter brave at some point is some sort of
rate-based policy like amazon's
http://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-sampling

like 100% up to a certain rate and then a fraction after. Really helpful
for beginners as 100% is good while just starting, but ends with a terrible
learning curve (as their system falls over) :)

**Comment by ramonza** [comment]
We need to make sure that we can still recover meaningful statistics over the stored traces. Maybe this just means we need to record in a standard place how many requests were skipped for tracing (because of sampling, or because of rate-limiting) for each trace we did sample i.e. how many traces it statistically "represents".

**Comment by songy23** [comment]
Already fixed in https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md.
