### ISSUE TITLE
Use same metric type and units in stats exporters

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#91]
Here is the specs for converting OC aggregations to metrics:
https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/Export.md#aggregation-to-metric

All languages must be consistent.

We will close this issue when all the languages that currently support stats implemented this:

- [x] C++
- [ ] Erlang
- [ ] Go
- [x] Java

**Comment by bogdandrutu** [comment]
Please mark as done for each language when this is implemented and tested.

**Comment by bogdandrutu** [comment]
Ping @songy23 @rakyll @tsloughter any update on your side?

**Comment by tsloughter** [comment]
I think almost on the Erlang side. Will be sure to update when it is complete.

**Comment by deadtrickster** [comment]
We don't separate float and int but otherwise erlang looks the same

**Comment by songy23** [comment]
For Java everything is consistent with specs except for LastValue (in progress).

**Comment by songy23** [comment]
OC Java is consistent with specs now after https://github.com/census-instrumentation/opencensus-java/pull/1055.

**Comment by songy23** [comment]
AFAIK this is fixed in all languages.
